version: '3.8'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://hcwuser:hcwpasswd@localhost:5432/hcw?schema=public
    depends_on:
      - db
    restart: always

  patient:
    build:
      context: patient
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - db
    restart: always

  admin:
    build:
      context: admin
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - db
    restart: always

  practitioner:
    build:
      context: practitioner
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
      - db
    restart: always

  db:
    image: docker.io/postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: hcwuser
      POSTGRES_PASSWORD: hcwpasswd
      POSTGRES_DB: hcw
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: